name: Sudo
author: ErikX
api:
  - 4.0.0
  - 5.0.0
version: 1.3
main: ErikX\sudo\Main

commands:
  sudo:
    description: "Sudo a player!"
    permission: "sudo.use"

permissions:
  sudo.use:
    description: "Permission to sudo a player!"
    default: op
